CREATE TABLE atributos (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						    nome VARCHAR(20) NOT NULL, cor VARCHAR(20) NOT NULL, icone_imagem VARCHAR(255));

CREATE TABLE talentos (id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					   			nome VARCHAR(255) NOT NULL, icone_imagem VARCHAR(255),
								atributo_id INTEGER  NOT NULL REFERENCES atributos (id)
                           	ON DELETE CASCADE
                            ON UPDATE CASCADE
);

CREATE TABLE nivel_talento(id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
									nivel INTEGER NOT NULL, descricao TEXT NOT NULL,
									talento_id INTEGER NOT NULL REFERENCES talentos (id)
                            	ON DELETE CASCADE
                            	ON UPDATE CASCADE
);