CREATE TABLE fichas_informacoes_basicas (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
						nome VARCHAR(255) NOT NULL, raca VARCHAR(30), nome_jogador VARCHAR(255) NOT NULL,
						nivel SMALLINT, experiencia INTEGER,
						iniciativa SMALLINT, tokens SMALLINT,
						vida_atual SMALLINT, vida_temporario SMALLINT,
						mana_atual SMALLINT, mana_temporario SMALLINT);

CREATE TABLE atributos_ficha (fichas_informacoes_basicas_id INTEGER REFERENCES fichas_informacoes_basicas(id),
						atributo_id INTEGER REFERENCES atributos (id), pontos SMALLINT,
						PRIMARY KEY (fichas_informacoes_basicas_id, atributo_id));

CREATE TABLE talentos_ficha (fichas_informacoes_basicas_id INTEGER REFERENCES fichas_informacoes_basicas(id),
						talento_id INTEGER REFERENCES talentos (id), pontos SMALLINT,
						PRIMARY KEY (fichas_informacoes_basicas_id, talento_id));