CREATE TABLE decisoes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tipo_de_decisao VARCHAR(255) );

CREATE TABLE opcoes_decisoes (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tipo_de_decisao_id INTEGER REFERENCES decisoes(id),
                        decisao VARCHAR(255));

CREATE TABLE decisoes_talentos_ficha (fichas_informacoes_basicas_id INTEGER,
						talento_id INTEGER,
						opcoes_decisoes_id INTEGER REFERENCES opcoes_decisoes(id),
						FOREIGN KEY (fichas_informacoes_basicas_id, talento_id) REFERENCES talentos_ficha(fichas_informacoes_basicas_id, talento_id),
						PRIMARY KEY (fichas_informacoes_basicas_id, talento_id, opcoes_decisoes_id));

INSERT INTO decisoes(tipo_de_decisao) VALUES
	('PROFICIENCIA_EM_COMBATE'),
    ('AFINIDADE_MAGICA'),
    ('PERICIA');

INSERT INTO opcoes_decisoes(tipo_de_decisao_id, decisao) VALUES
	(1, 'Desarmado'),
	(1, 'Armas brancas e Escudo'),
	(1, 'Armas de longo alcance'),
    (2, 'Fogo'),
    (2, 'Tempestade'),
    (2, 'Gelo'),
    (3, 'Atletismo'),
    (3, 'Acrobacia'),
    (3, 'Furtividade'),
    (3, 'Sagacidade'),
    (3, 'Carisma'),
    (3, 'Sobrevivência'),
    (3, 'Prontidão'),
    (3, 'Coragem'),
    (3, 'Sentir Magia');

ALTER TABLE nivel_talento ADD COLUMN tipo_de_decisao INTEGER REFERENCES decisoes(id);
UPDATE nivel_talento SET tipo_de_decisao = 1 WHERE id IN (16, 17, 18);
UPDATE nivel_talento SET tipo_de_decisao = 2 WHERE id IN (79, 80, 81);
UPDATE nivel_talento SET tipo_de_decisao = 3 WHERE id IN (34, 35, 36);

CREATE TABLE manobras(id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					        genero_de_manobra VARCHAR(255) NOT NULL, nome VARCHAR(255) NOT NULL, descricao TEXT NOT NULL, url_imagem VARCHAR(255)
);

---------------------Inserir Caminhos
INSERT INTO manobras(genero_de_manobra, nome, descricao) VALUES
('ARMAS_BRANCAS_E_ESCUDO','Transpassar','Quando realizar ataques com armas de corte, você pode acertar UM alvo adjacente ao alvo primário. O valor do segundo ataque é reduzido em -10. Se o alvo primário fizer uma Esquiva segurando um escudo, a manobra é anulada.'),
('ARMAS_BRANCAS_E_ESCUDO','Deslocar','Você pode realizar a ação de Empurrar/Derrubar atacando com uma arma de consussão ou golpes desarmados.'),
('ARMAS_BRANCAS_E_ESCUDO','Defensor',' Enquanto você segurar um escudo, você pode usar Esquiva para adicionar seu bônus em um alvo próximo.'),
('ARMAS_BRANCAS_E_ESCUDO','Desarmar',' Pré-requisito (Furtividade): Quando realizar um golpe corpo a corpo com uma arma ou desarmado, você pode tentar desarmar o alvo. Essa manobra não causa dano, mas os valores de golpe são utilizados para comparar com a Resistência Passiva.<br>- Você tem desvantabem contra armas que estiverem sendo seguradas pelas duas mãos ou uma criatura maior do que você.'),
('IMBUIR_COM_MANA', ' Fonte Elemental', 'Pré-requisito (Afinidade Elemental): Você não precisa pagar o custo de 1MP no ataque desarmado para aplicar dano elemental.'),
('IMBUIR_COM_MANA', 'Charme','Pré-requisito (Carisma): Sempre que utilizar Carisma, você pode escolher UMA carta Vermelha para ter seu valor contabilizado, pode adicionar mais cartas vermelhas gastando 1MP para cada carta adicional.'),
('IMBUIR_COM_MANA', 'Xamã','Pré-requisito (Sobrevivência nível 2): Você pode gastar MP para afetar fauna e a flora magicamente. Quanto maior o efeito, maior o custo de MP.'),
('IMBUIR_COM_MANA', 'Arcano', 'Pré-requisito (Perícia: Sentir Magia): Você pode gastar 1MP para somar cartas AZUIS em testes do atributo Magia. Ganha 1MP máximo para cada PONTO de Perícia.'),
('IMBUIR_COM_MANA', 'Elemento Espiritual', 'Pré-requisito (Coragem nível 2): Você adquire afinidade elemental com um desses elementos: Luz ou Sombra.'),
('MUSICA', 'Revigorar', 'Pré-requisito (Inspirar e Instrumento mágico): Sempre que usar Inspirar, pelo custo de 2HP você recuperar 2HP do alvo inspirado.'),
('MUSICA', 'Ritmo de Batalha', 'Pré-requisito (Inspirar e Instrumento mágico): para cada 10 pontos na ação de música(Sagacidade-Inteligência), você garante um bônus de +1 no IP e Ataque para você e seus aliados até o começo do seu próximo turno.<br>É preciso manter a concentração.'),
('MUSICA', 'Descontrair e Motivar', 'Pré-requisito (Carisma e Sagacidade): você consegue aprimorar o descanso e motivar todos seus aliados que estiverem próximos. Você faz um teste de Carisma(int) ou Sagacidade(int), para cada 5 pontos nesse teste, você recupera 1HP e da um bônus de 1HP temporário pelas próximas 12h.'),
('DESARMADO', 'Lutador','Quando realizar 2 ataques em sequência com no mínimo 1 golpe desarmado, o segundo ataque não precisa usar carta.'),
('DESARMADO', 'Briga', 'Pré-requisito (Atletismo): Você pode realizar a ação de Agarrar atacando com um golpe desarmado.'),
('DESARMADO', 'Dobramágica', 'Pré-requisito (Aptidão Mágica): Para cada mão livre, você pode escolher uma carta de cor Vermelha para ter seu valor completo contabilizado em uma magia.'),
('LONGA_DISTANCIA', 'Mira', 'No final do seu turno você escolher mirar em um alvo, se conseguir manter a concentração, seu primeiro ataque no próximo turno contra o alvo mirado é feito com VANTAGEM. Andar, reagir ou realizar qualquer outra ação anula a mira e aplica desvantagem na sua ação.'),
('LONGA_DISTANCIA', 'Flechas Múltiplas', 'Quando realizar UM ataque com arco e flecha, você pode usar DUAS ações para:<br>Atirar duas flechas, podendo acertar o mesmo alvo ou 2 alvos adjacentes.<br>Atirar três flechas, podendo acertar o mesmo alvo ou 3 alvos adjacentes. É preciso queimar uma carta.'),
('LONGA_DISTANCIA', 'Foco' ,' Se segurar uma arma de longo alcance com às duas mãos, você causa +1 de dano por sucesso.'),
('LONGA_DISTANCIA', 'Ponto Fraco', 'Pré-requisito (Oportunista): Quando causar dano de perfuração, você ignora o IP bonus da Esquiva.');